os: linux
dist: xenial
language: python
python:
  - "3.7"
  - "3.6"
env: TOXENV=py,codecov

matrix:
  include:
    - env: TOXENV=docs-html
    - env: TOXENV=devel,lowest,codecov

  allow_failures:
    - python: nightly
    - python: pypy3.5-6.0
    - os: osx
  fast_finish: true

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      brew upgrade python
      export PATH="/usr/local/opt/python/libexec/bin:${PATH}"
    fi
install:
  - pip install tox

script:
  - tox

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

branches:
  only:
    - master
    - /^\d+(\.\d+)*-maintenance$/
    - /^\d+(\.\d+)*(\.x)?$/

notifications:
  email: false