version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    branches:
      ignore:
        - gh-pages

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements/dev.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements/dev.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest --cov .
            coverage report --fail-under=90

      - run:
          name: run linting
          command: |
            . venv/bin/activate
            flake8 --exclude venv,.egg,.eggs --ignore E501,E127

      - store_artifacts:
          path: test-reports
          destination: test-reports

  test37:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.7.1

    working_directory: ~/repo

    branches:
      ignore:
        - gh-pages

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements/dev.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv37
            . venv37/bin/activate
            pip install -r requirements/dev.txt

      - save_cache:
          paths:
            - ./venv37
          key: v2-dependencies-{{ checksum "requirements/dev.txt" }}

      - run:
          name: run tests
          command: |
            . venv37/bin/activate
            python -m pytest --cov .
            coverage report --fail-under=90
