version: 2

jobs:

  build:
    working_directory: ~/.
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true

    steps: &steps
        - checkout
        - run: sudo pip install -r requirements/dev.txt
        - run: python --version ; pip --version ; pwd ; ls
        # stop the build if there are Python syntax errors or undefined names
        - run: flake8 --exclude .egg,.eggs --ignore E501,E127
        - run: python -m pytest --cov .
        - run: coverage report --fail-under=90

    Python_3.6:
      docker:
        - image: circleci/python:3.6
      steps: *steps


workflows:
  version: 2
  build:
    jobs:
      - Python_3.6